fos_user:
    db_driver: orm
    firewall_name: api
    user_class: App\Entity\User
    service:
        mailer: fos_user.mailer.noop
    from_email:
        address:        noreply@openchurch.fr
        sender_name:    noreply OpenChurch
