version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch
    environment:
    - ES_JAVA_OPTS=-Xms750m -Xmx750m
    - discovery.type=single-node
    - network.host=172.18.0.4
    ports:
    - 9200:9200
    networks:
      ocnet:
        ipv4_address: 172.18.0.4

  openchurch:
    build: .
    image: hozana/openchurch
    command: apachectl -D "FOREGROUND"
    container_name: openchurch
    links:
    - db
    depends_on:
    - db
    volumes:
    - ./:/var/www
    ports:
    - 1819:80
    env_file: ./.env
    networks:
      ocnet:
        ipv4_address: 172.18.0.1

  db:
    image: mysql:latest
    container_name: db
    volumes:
    - ./data/data/20180806-openchurch.sql:/docker-entrypoint-initdb.d/
    #- ./tools/docker/mysql:/etc/mysql/conf.d
    ports:
    - 13306:3306
    env_file: ./.env
    networks:
      ocnet:
        ipv4_address: 172.18.0.5

networks:
  ocnet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.18.0.0/16
        gateway: 172.18.0.1
