version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch
    environment:
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
    - 9200:9200
    network_mode: "bridge"

  openchurch:
    build: .
    image: hozana/openchurch
    command: apachectl -D "FOREGROUND"
    container_name: openchurch
    links:
    - db
    depends_on:
    - db
    volumes:
    - ./:/var/www
    ports:
    - 1819:80
    env_file: ./.env
    network_mode: "bridge"

  db:
    image: mysql:latest
    container_name: db
    volumes:
    - ./.dev/mysql:/var/lib/mysql
    - ./.dev/dump:/docker-entrypoint-initdb.d
    #- ./tools/docker/mysql:/etc/mysql/conf.d
    ports:
    - 13306:3306
    env_file: ./.env
    network_mode: "bridge"

networks:
  default:
    driver: bridge
