version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch
    environment:
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
    - 9200:9200
