types:
    Places:
        parent: false
        properties:
            parentId: { range: Places, cardinality: (0..1) }
            name: { range: Text }
            type: { range: PlaceTypes }
            createdAt: { range: DateTime, nullable: true }
            updatedAt: { range: DateTime, nullable: true }
    Calendars:
        parent: false
        properties:
            churchId: { range: Churches }
            calendarUrl: { range: Text, nullable: true }
            rite: { range: Rites }
            lang: { range: Text }
            type: { range: CalendarTypes }
            createdAt: { range: DateTime, nullable: true }
            updatedAt: { range: DateTime, nullable: true }
    TheodiaChurches:
        parent: false
        properties:
            createdAt: { range: DateTime, nullable: true }
            updatedAt: { range: DateTime, nullable: true }
    Churches:
        parent: false
        properties:
            wikidataId: { range: WikidataChurches }
            theodiaId: { range: TheodiaChurches }
    Photos:
        parent: false
        properties:
            url: { range: Text }
            createdAt: { range: DateTime, nullable: true }
            updatedAt: { range: DateTime, nullable: true }
    WikidataChurches:
        parent: false
        properties:
            name: { range: Text }
            photoId: { range: Photos }
            latitude: { range: Number }
            longitude: { range: Number }
            placeId: { range: Places }
            address: { range: Text }
            hozanaUserId: { range: Integer, nullable: True }
            createdAt: { range: DateTime, nullable: true }
            updatedAt: { range: DateTime, nullable: true }
